- name: Generate SBOM
  run: cyclonedx-bom -o sbom.json

- name: Verify SBOM File
  run: ls -l sbom.json

- name: Debug Artifact File
  run: |
    echo "Listing current directory:"
    ls -al
    echo "Checking sbom.json:"
    cat sbom.json

- name: Upload SBOM
  uses: actions/upload-artifact@v3
  with:
    name: sbom
    path: sbom.json
