name: Generate SBOM

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Generate SBOM (CycloneDX)
        run: |
          npx @cyclonedx/bom -o sbom.json
          mkdir -p sbom_output
          mv sbom.json sbom_output/

      - name: Commit SBOM to repo (optional)
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add sbom_output/sbom.json
          git commit -m "Add SBOM output"
          git push || echo "Nothing to push"
