name: Generate SBOM

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Install CycloneDX locally
        run: npm install @cyclonedx/bom --save-dev

      - name: Generate SBOM
        run: |
          npx cyclonedx-bom -o sbom.json || echo "SBOM generation failed"
          mkdir -p sbom_output
          mv sbom.json sbom_output/ || echo "No SBOM to move"

      - name: List files in sbom_output
        run: ls -l sbom_output || echo "sbom_output not found"

      - name: Upload SBOM artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: sbom
          path: sbom_output/sbom.json
