name: Generate SBOM

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install CycloneDX module
        run: npm install -g @cyclonedx/bom

      - name: Install dependencies
        run: npm install

      - name: Generate SBOM
        run: cyclonedx-bom -o sbom.json

      - name: Upload SBOM
        uses: actions/upload-artifact@v3
        with:
          name: sbom
          path: sbom.json
